import { Asset, Category } from "@/types";

export const dummyCategories: Category[] = [
  { id: "1", name: "日本の食", slug: "japanese-food", count: 120 },
  { id: "2", name: "医療・歯科", slug: "medical-dental", count: 85 },
  { id: "3", name: "事務用品", slug: "office-supplies", count: 64 },
  { id: "4", name: "年中行事", slug: "annual-events", count: 92 },
  { id: "5", name: "日本の日常小物", slug: "daily-items", count: 110 },
];

export const dummyAssets: Asset[] = [
  {
    id: "sushi-01",
    title: "特上 握り寿司セット",
    category: "日本の食",
    tags: ["寿司", "和食", "ランチ"],
    description: "AIによって生成された高品質な寿司の背景透過画像です。握り寿司のリアルな質感と、透明感のある仕上がりが特徴です。",
    imageUrl: "https://pngimg.com/uploads/sushi/sushi_PNG9202.png",
    thumbnailUrl: "https://pngimg.com/uploads/sushi/sushi_PNG9202.png",
    storageKey: "assets/sushi-01.png",
    width: 4000,
    height: 3000,
    fileSize: "4.2 MB",
    isAiGenerated: true,
    isCommercialOk: true,
    licenseType: "free",
    reviewStatus: "approved",
    legalStatus: "clean",
  },
  {
    id: "dental-01",
    title: "歯科用ハンドピース・ミラー",
    category: "医療・歯科",
    tags: ["歯医者", "医療機器", "ホワイトニング"],
    description: "清潔感のある歯科用器具のセットです。医療系のバナーや説明資料に最適です。",
    imageUrl: "https://pngimg.com/uploads/medical_items/medical_items_PNG11.png",
    thumbnailUrl: "https://pngimg.com/uploads/medical_items/medical_items_PNG11.png",
    storageKey: "assets/dental-01.png",
    width: 3500,
    height: 3500,
    fileSize: "3.8 MB",
    isAiGenerated: true,
    isCommercialOk: true,
    licenseType: "free",
    reviewStatus: "approved",
    legalStatus: "clean",
  },
  {
    id: "office-01",
    title: "高級 万年筆とノート",
    category: "事務用品",
    tags: ["文房具", "ビジネス", "書斎"],
    description: "重厚感のある万年筆と上質なノートのセット。ビジネスシーンのビジュアルに最適です。",
    imageUrl: "https://pngimg.com/uploads/pen/pen_PNG1395.png",
    thumbnailUrl: "https://pngimg.com/uploads/pen/pen_PNG1395.png",
    storageKey: "assets/office-01.png",
    width: 3000,
    height: 2000,
    fileSize: "2.1 MB",
    isAiGenerated: true,
    isCommercialOk: true,
    licenseType: "free",
    reviewStatus: "approved",
    legalStatus: "clean",
  },
  {
    id: "event-01",
    title: "お正月 鏡餅と飾り",
    category: "年中行事",
    tags: ["正月", "新年", "伝統"],
    description: "日本の伝統的なお正月の飾り、鏡餅の透過PNG画像。新年の挨拶やチラシ制作に。",
    imageUrl: "https://pngimg.com/uploads/new_year/new_year_PNG66.png",
    thumbnailUrl: "https://pngimg.com/uploads/new_year/new_year_PNG66.png",
    storageKey: "assets/event-01.png",
    width: 4000,
    height: 4000,
    fileSize: "5.5 MB",
    isAiGenerated: true,
    isCommercialOk: true,
    licenseType: "free",
    reviewStatus: "approved",
    legalStatus: "clean",
  },
  {
    id: "daily-01",
    title: "急須と湯呑みセット",
    category: "日本の日常小物",
    tags: ["お茶", "和室", "リラックス"],
    description: "温かみのある急須と湯呑みのセット。和風のデザインやライフスタイルのコンテンツに。",
    imageUrl: "https://pngimg.com/uploads/teapot/teapot_PNG27.png",
    thumbnailUrl: "https://pngimg.com/uploads/teapot/teapot_PNG27.png",
    storageKey: "assets/daily-01.png",
    width: 3200,
    height: 2800,
    fileSize: "3.2 MB",
    isAiGenerated: true,
    isCommercialOk: true,
    licenseType: "free",
    reviewStatus: "approved",
    legalStatus: "clean",
  }
];

export const popularTags = [
  "ラーメン", "ビジネス", "桜", "富士山", "笑顔", "着物", "電車", "学校", "祭り"
];
