"use client";

import React, { useState, useEffect, useRef, useCallback } from "react";
import { Play, Square, Loader2, AlertTriangle, CheckCircle, Database, Clock, Zap, Activity, Radar } from "lucide-react";
import { supabase } from "@/lib/supabase";

export default function AssetProductionCenter() {
  const [targetCount, setTargetCount] = useState<number>(10);
  const [isRunning, setIsRunning] = useState(false);
  const [isShuttingDown, setIsShuttingDown] = useState(false);
  
  const [stats, setStats] = useState({
    processed: 0,
    success: 0,
    fail: 0,
    published: 0,
  });
  
  const [dbStats, setDbStats] = useState({
    totalAssets: 0,
    totalApproved: 0,
    realQueued: 0,
    dryRunArchived: 0,
    globalQaFailed: 0,
    // Phase 3 Additions
    todaySearchCount: 0,
    needAssetCount: 0,
    autoGenCandidates: 0,
    qaPassRate: 0,
    totalDownloads: 0,
    estimatedAdRev: 0,
  });
  
  const [logs, setLogs] = useState<string[]>([]);
  const [currentAction, setCurrentAction] = useState("待機中");

  // Auto Mode States
  const [autoModeEnabled, setAutoModeEnabled] = useState(false);
  const [idleWatchEnabled, setIdleWatchEnabled] = useState(true);
  const [autoBatchSize, setAutoBatchSize] = useState<number>(10);
  const [autoDailyLimit, setAutoDailyLimit] = useState<number>(20);
  const [autoCooldownMinutes, setAutoCooldownMinutes] = useState<number>(180);
  
  // Auto Mode Execution States
  const [lastAutoRunTime, setLastAutoRunTime] = useState<number>(0);
  const [todayAutoGenerated, setTodayAutoGenerated] = useState<number>(0);
  const [lastActivityTime, setLastActivityTime] = useState<number>(Date.now());
  const [autoStatusMsg, setAutoStatusMsg] = useState<string>("初期化中...");
  const [lastAutoRunDateStr, setLastAutoRunDateStr] = useState<string>("");
  const [nextRunTime, setNextRunTime] = useState<string>("");

  const shouldRunRef = useRef(false);
  const statsRef = useRef(stats);
  const targetRef = useRef(targetCount);
  const autoModeRef = useRef(autoModeEnabled);

  // Keep refs in sync for the async loop
  useEffect(() => { statsRef.current = stats; }, [stats]);
  useEffect(() => { targetRef.current = targetCount; }, [targetCount]);
  useEffect(() => { autoModeRef.current = autoModeEnabled; }, [autoModeEnabled]);

  const addLog = useCallback((msg: string) => {
    setLogs(prev => {
      const newLogs = [...prev, `[${new Date().toLocaleTimeString()}] ${msg}`];
      return newLogs.length > 50 ? newLogs.slice(newLogs.length - 50) : newLogs;
    });
  }, []);

  const fetchDbStats = async () => {
    try {
      const res = await fetch('/api/admin/generation-jobs/stats');
      if (res.ok) {
        const data = await res.json();
        
        // Fetch Demand Radar Stats (Phase 3)
        const demandRes = await fetch('/api/admin/demand-radar/stats');
        const demandData = demandRes.ok ? await demandRes.json() : {};
        
        setDbStats({
          totalAssets: data.actualGenerated || 0,
          totalApproved: data.totalApproved || 0,
          realQueued: data.realQueued || 0,
          dryRunArchived: data.dryRunArchived || 0,
          globalQaFailed: data.globalQaFailed || 0,
          // Phase 3
          todaySearchCount: demandData.todaySearchCount || 0,
          needAssetCount: demandData.needAssetCount || 0,
          autoGenCandidates: demandData.autoGenCandidates || 0,
          qaPassRate: data.actualGenerated ? Math.round((data.totalApproved / data.actualGenerated) * 100) : 0,
          totalDownloads: demandData.totalDownloads || 0,
          estimatedAdRev: demandData.totalDownloads ? demandData.totalDownloads * 0.15 : 0, // Mock calculation
        });
      }
    } catch (e) {
      console.error(e);
    }
  };

  useEffect(() => {
    fetchDbStats();
  }, []);

  // --- Load / Save Auto Mode Settings ---
  useEffect(() => {
    const loadConf = (key: string, defaultVal: any) => {
      if (typeof window === 'undefined') return defaultVal;
      const v = localStorage.getItem(key);
      if (v === null) return defaultVal;
      try { return JSON.parse(v); } catch(e) { return v; }
    };
    
    setAutoModeEnabled(loadConf("assetninja_auto_mode_enabled", false));
    setIdleWatchEnabled(loadConf("assetninja_idle_watch_enabled", true));
    setAutoBatchSize(loadConf("assetninja_auto_batch_size", 10));
    setAutoDailyLimit(loadConf("assetninja_auto_daily_limit", 20));
    setAutoCooldownMinutes(loadConf("assetninja_auto_cooldown_minutes", 180));
    
    const todayStr = new Date().toISOString().split('T')[0];
    const savedDateStr = loadConf("assetninja_auto_last_date", "");
    if (savedDateStr !== todayStr) {
      setTodayAutoGenerated(0);
      localStorage.setItem("assetninja_auto_last_date", todayStr);
      setLastAutoRunDateStr(todayStr);
    } else {
      setTodayAutoGenerated(loadConf("assetninja_auto_today_generated", 0));
      setLastAutoRunDateStr(todayStr);
    }
    
    setLastAutoRunTime(loadConf("assetninja_auto_last_run_time", 0));
  }, []);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem("assetninja_auto_mode_enabled", JSON.stringify(autoModeEnabled));
      localStorage.setItem("assetninja_idle_watch_enabled", JSON.stringify(idleWatchEnabled));
      localStorage.setItem("assetninja_auto_batch_size", JSON.stringify(autoBatchSize));
      localStorage.setItem("assetninja_auto_daily_limit", JSON.stringify(autoDailyLimit));
      localStorage.setItem("assetninja_auto_cooldown_minutes", JSON.stringify(autoCooldownMinutes));
      localStorage.setItem("assetninja_auto_today_generated", JSON.stringify(todayAutoGenerated));
      localStorage.setItem("assetninja_auto_last_run_time", JSON.stringify(lastAutoRunTime));
    }
  }, [autoModeEnabled, idleWatchEnabled, autoBatchSize, autoDailyLimit, autoCooldownMinutes, todayAutoGenerated, lastAutoRunTime]);

  // --- Idle Tracking ---
  useEffect(() => {
    const updateActivity = () => setLastActivityTime(Date.now());
    window.addEventListener('mousemove', updateActivity);
    window.addEventListener('keydown', updateActivity);
    window.addEventListener('scroll', updateActivity);
    window.addEventListener('touchstart', updateActivity);
    return () => {
      window.removeEventListener('mousemove', updateActivity);
      window.removeEventListener('keydown', updateActivity);
      window.removeEventListener('scroll', updateActivity);
      window.removeEventListener('touchstart', updateActivity);
    };
  }, []);

  const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

  // Forward declaration for auto execution
  const startGenerationRef = useRef<(() => void) | undefined>(undefined);

  const startGeneration = useCallback(async () => {
    if (isRunning) return;
    
    // Reset session stats
    setStats({ processed: 0, success: 0, fail: 0, published: 0 });
    setLogs([]);
    setIsRunning(true);
    setIsShuttingDown(false);
    shouldRunRef.current = true;
    
    addLog(`生産センター起動: 目標 ${targetRef.current} 件`);
    
    let currentProcessed = 0;
    
    while (shouldRunRef.current && currentProcessed < targetRef.current) {
      setCurrentAction(`API呼び出し中... (${currentProcessed}/${targetRef.current})`);
      
      const batchSize = Math.min(2, targetRef.current - currentProcessed); 
      
      try {
        const res = await fetch('/api/admin/generation-jobs/run', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-agent-token': 'temp-agent-token-123'
          },
          body: JSON.stringify({ limit: batchSize })
        });
        
        if (!res.ok) {
          const responseText = await res.text();
          let json = null;
          try { json = JSON.parse(responseText); } catch(e) {}
          
          console.log("API Error details:", {
            status: res.status,
            responseText,
            json
          });

          // Vercel Serverless Timeout (500/504) Mitigation
          // The function might have been killed by API Gateway, but continues in the background.
          // Let's wait a bit and check if the database was actually updated.
          addLog(`API警告: HTTP ${res.status} (タイムアウト疑い)`);
          setCurrentAction("バックグラウンド処理確認中...");
          
          await sleep(10000); // Wait 10 seconds for lambda to finish
          
          const prevApproved = statsRef.current.published;
          const { count: currentApproved } = await supabase.from('assets').select('*', { count: 'exact', head: true }).like('storage_key', 'real/%').eq('review_status', 'approved');
          
          const globalApprovedDelta = (currentApproved || 0) - dbStats.totalApproved;
          
          if (globalApprovedDelta > 0) {
            addLog(`-> バックグラウンドでの生成成功を確認 (+${globalApprovedDelta}件)`);
            setStats(prev => ({
              ...prev,
              processed: prev.processed + globalApprovedDelta,
              success: prev.success + globalApprovedDelta,
              published: prev.published + globalApprovedDelta,
            }));
            currentProcessed += globalApprovedDelta;
            await fetchDbStats();
            setCurrentAction("待機中 (30秒)...");
            await sleep(30000);
            continue;
          } else {
            addLog(`APIエラー確定: サーバー応答なし`);
            setCurrentAction("APIエラー待機中 (30秒)...");
            await sleep(30000);
            continue;
          }
        }
        
        const data = await res.json();
        
        if (!data.success && data.error === 'RATE_LIMIT_WAIT') {
          const waitMs = Math.floor(Math.random() * (30 * 60000 - 15 * 60000 + 1)) + 15 * 60000;
          addLog(`⚠️ Rate Limit到達。${Math.round(waitMs/60000)}分間待機します...`);
          setCurrentAction(`Rate Limit待機中 (${Math.round(waitMs/60000)}分)`);
          
          const steps = waitMs / 5000;
          for (let i = 0; i < steps; i++) {
            if (!shouldRunRef.current) break;
            await sleep(5000);
          }
          continue;
        }
        
        if (data.results && data.results.length > 0) {
          currentProcessed += data.results.length;
          
          let successDelta = 0;
          let failDelta = 0;
          let publishedDelta = 0;
          
          data.results.forEach((r: any) => {
            addLog(`-> [${r.status}] ${r.keyword || r.id}`);
            if (r.status === 'qa_passed') {
              successDelta++;
              publishedDelta++;
            } else if (r.status === 'qa_failed' || r.status === 'failed') {
              failDelta++;
            }
          });
          
          setStats(prev => ({
            processed: prev.processed + data.results.length,
            success: prev.success + successDelta,
            fail: prev.fail + failDelta,
            published: prev.published + publishedDelta,
          }));
          
          await fetchDbStats();
          
        } else {
          addLog("処理可能なキューがありませんでした。");
          break; 
        }
        
        if (currentProcessed >= targetRef.current || !shouldRunRef.current) break;
        
        setCurrentAction("待機中 (30秒)...");
        for (let i = 0; i < 6; i++) {
          if (!shouldRunRef.current) break;
          await sleep(5000);
        }
        
      } catch (err: any) {
        addLog(`実行エラー: ${err.message}`);
        setCurrentAction("エラー待機中 (30秒)...");
        await sleep(30000);
      }
    }
    
    addLog(`生産センター停止。処理完了: ${currentProcessed} 件`);
    setCurrentAction("待機中");
    setIsRunning(false);
    setIsShuttingDown(false);
    shouldRunRef.current = false;
  }, [isRunning, addLog]);

  useEffect(() => {
    startGenerationRef.current = startGeneration;
  }, [startGeneration]);

  const stopGeneration = () => {
    if (!isRunning) {
      // Force disable Auto Mode as a safety measure
      setAutoModeEnabled(false);
      return;
    }
    setIsShuttingDown(true);
    shouldRunRef.current = false;
    setAutoModeEnabled(false);
    addLog("停止シグナル送信... (Auto Mode OFF)");
    setCurrentAction("停止準備中...");
  };

  // --- Auto Check Loop ---
  useEffect(() => {
    const checkInterval = setInterval(() => {
      // Next run time calc
      const nextRunMs = lastAutoRunTime + autoCooldownMinutes * 60 * 1000;
      if (Date.now() < nextRunMs && lastAutoRunTime > 0) {
        setNextRunTime(new Date(nextRunMs).toLocaleTimeString());
      } else {
        setNextRunTime("実行可能");
      }

      if (!autoModeEnabled) {
        setAutoStatusMsg("Auto Mode OFF");
        return;
      }
      if (isRunning) {
        setAutoStatusMsg("手動・自動生成実行中");
        return;
      }
      
      const todayStr = new Date().toISOString().split('T')[0];
      let currentTodayCount = todayAutoGenerated;
      if (lastAutoRunDateStr && lastAutoRunDateStr !== todayStr) {
        setTodayAutoGenerated(0);
        localStorage.setItem("assetninja_auto_last_date", todayStr);
        setLastAutoRunDateStr(todayStr);
        currentTodayCount = 0;
      }

      if (currentTodayCount >= autoDailyLimit) {
        setAutoStatusMsg("Daily Limit到達");
        return;
      }
      
      if (Date.now() - lastAutoRunTime < autoCooldownMinutes * 60 * 1000) {
        setAutoStatusMsg("Cooldown待機中");
        return;
      }
      
      if (idleWatchEnabled) {
        if (document.visibilityState !== 'visible') {
          setAutoStatusMsg("バックグラウンド待機中");
          return;
        }
        if (!navigator.onLine) {
          setAutoStatusMsg("オフライン待機中");
          return;
        }
        if (Date.now() - lastActivityTime < 5 * 60 * 1000) {
          setAutoStatusMsg("通信アイドル(無操作)待ち");
          return;
        }
      }
      
      // All conditions passed, execute
      setAutoStatusMsg("自動生成実行開始！");
      setTargetCount(autoBatchSize);
      setTodayAutoGenerated(prev => prev + autoBatchSize);
      setLastAutoRunTime(Date.now());
      
      addLog(`[Auto Mode] 条件クリア。自動生成開始: ${autoBatchSize}件`);
      
      setTimeout(() => {
        if (startGenerationRef.current) startGenerationRef.current();
      }, 500);

    }, 5000); // 5秒ごとにチェック
    
    return () => clearInterval(checkInterval);
  }, [autoModeEnabled, isRunning, autoBatchSize, autoDailyLimit, autoCooldownMinutes, idleWatchEnabled, todayAutoGenerated, lastAutoRunTime, lastActivityTime, lastAutoRunDateStr, addLog]);


  // Calculate Estimates
  const estimatedSeconds = targetCount * 35; // About 35s per asset based on logic. But wait, UI requests "1件あたり5.5分で計算". Let's update that.
  const estMins = Math.floor(targetCount * 5.5);
  // UI Format: 約1時間50分 etc
  const estHoursDisp = Math.floor(estMins / 60);
  const estMinsDisp = estMins % 60;
  
  const estDisplay = estHoursDisp > 0 
    ? `約 ${estHoursDisp}時間${estMinsDisp}分` 
    : `約 ${estMins}分`;

  const expectedPublished = Math.floor(targetCount * 0.8); // QA rate 80%
  
  const progressPercent = targetCount > 0 ? Math.min(100, Math.round((stats.processed / targetCount) * 100)) : 0;
  const globalProgress = Math.min(100, Math.round((dbStats.totalApproved / 100) * 100));

  return (
    <div className="bg-gradient-to-br from-indigo-900/40 to-purple-900/20 border border-indigo-500/30 rounded-2xl p-6 relative overflow-hidden mb-8 shadow-xl">
      <div className="absolute top-0 right-0 p-8 opacity-10">
        <Database size={120} />
      </div>
      
      <div className="relative z-10">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <div className="p-3 bg-indigo-500/20 rounded-xl text-indigo-400">
              <Database size={24} />
            </div>
            <div>
              <h2 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 to-purple-400">
                Asset Production Center
              </h2>
              <p className="text-zinc-400 text-sm mt-1">アセット生産センター (ブラウザ常駐型自動生成ループ)</p>
            </div>
          </div>
          
          <div className="flex gap-2">
            {[1, 5, 10, 20, 50].map(num => (
              <button
                key={num}
                onClick={() => !isRunning && setTargetCount(num)}
                disabled={isRunning}
                className={`px-4 py-2 rounded-lg font-medium transition-all ${
                  targetCount === num 
                    ? 'bg-indigo-500 text-white shadow-lg shadow-indigo-500/20' 
                    : 'bg-zinc-800/50 text-zinc-400 hover:bg-zinc-800 disabled:opacity-50'
                }`}
              >
                {num}件
              </button>
            ))}
          </div>
        </div>

        {/* ----- AUTO MODE PANEL ----- */}
        <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-5 mb-6">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2 text-indigo-400 font-bold text-lg">
              <Zap size={20} />
              Auto Mode Settings
            </div>
            <div className="flex gap-4">
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold text-zinc-400">通信アイドル監視</span>
                <button
                  onClick={() => setIdleWatchEnabled(!idleWatchEnabled)}
                  className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${idleWatchEnabled ? 'bg-indigo-500' : 'bg-zinc-700'}`}
                >
                  <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${idleWatchEnabled ? 'translate-x-6' : 'translate-x-1'}`} />
                </button>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold text-zinc-400">Auto Mode</span>
                <button
                  onClick={() => setAutoModeEnabled(!autoModeEnabled)}
                  className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${autoModeEnabled ? 'bg-emerald-500' : 'bg-zinc-700'}`}
                >
                  <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${autoModeEnabled ? 'translate-x-6' : 'translate-x-1'}`} />
                </button>
              </div>
            </div>
          </div>
          
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-4">
            <div>
              <label className="text-[10px] text-zinc-500 block mb-1">自動生成件数</label>
              <select 
                value={autoBatchSize} 
                onChange={(e) => setAutoBatchSize(Number(e.target.value))}
                className="w-full bg-zinc-900 border border-zinc-700 rounded-lg p-2 text-sm text-white focus:outline-none focus:border-indigo-500"
                disabled={autoModeEnabled}
              >
                <option value={1}>1件 (Test)</option>
                <option value={10}>10件</option>
                <option value={20}>20件</option>
                <option value={50}>50件</option>
                <option value={100}>100件</option>
              </select>
            </div>
            <div>
              <label className="text-[10px] text-zinc-500 block mb-1">1日の上限</label>
              <select 
                value={autoDailyLimit} 
                onChange={(e) => setAutoDailyLimit(Number(e.target.value))}
                className="w-full bg-zinc-900 border border-zinc-700 rounded-lg p-2 text-sm text-white focus:outline-none focus:border-indigo-500"
                disabled={autoModeEnabled}
              >
                <option value={10}>10件</option>
                <option value={20}>20件</option>
                <option value={50}>50件</option>
              </select>
            </div>
            <div>
              <label className="text-[10px] text-zinc-500 block mb-1">本日生成数</label>
              <div className="w-full bg-zinc-900/50 border border-zinc-800 rounded-lg p-2 text-sm text-indigo-300 font-mono">
                {todayAutoGenerated} / {autoDailyLimit}
              </div>
            </div>
            <div>
              <label className="text-[10px] text-zinc-500 block mb-1">次回実行可能</label>
              <div className="w-full bg-zinc-900/50 border border-zinc-800 rounded-lg p-2 text-sm text-emerald-400 font-mono">
                {nextRunTime}
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-2 p-3 bg-zinc-900 rounded-lg border border-zinc-800">
            <Activity size={16} className="text-indigo-400" />
            <span className="text-xs text-zinc-400">現在の状態:</span>
            <span className={`text-sm font-bold ${autoModeEnabled ? 'text-emerald-400' : 'text-zinc-500'}`}>
              {autoStatusMsg}
            </span>
          </div>
        </div>
        {/* ----- END AUTO MODE PANEL ----- */}

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
          <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-4">
            <div className="text-zinc-500 text-xs mb-1 flex items-center gap-1"><Clock size={12}/> 推定所要時間</div>
            <div className="text-xl font-semibold text-zinc-200">
              {estDisplay}
            </div>
          </div>
          <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-4">
            <div className="text-zinc-500 text-xs mb-1 flex items-center gap-1"><CheckCircle size={12}/> 予測公開数</div>
            <div className="text-xl font-semibold text-emerald-400">約 {expectedPublished} 件</div>
          </div>
          <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-4">
            <div className="text-zinc-500 text-xs mb-1">ステータス (手動)</div>
            <div className="text-sm font-medium text-indigo-300 flex items-center gap-2">
              {isRunning && !isShuttingDown && <Loader2 size={14} className="animate-spin" />}
              {currentAction}
            </div>
          </div>
          <div className="flex items-center gap-2">
            {!isRunning ? (
              <button 
                onClick={() => {
                  setAutoModeEnabled(false);
                  startGeneration();
                }}
                className="flex-1 bg-gradient-to-r from-emerald-500 to-emerald-600 hover:from-emerald-400 hover:to-emerald-500 text-white font-bold rounded-xl p-4 flex items-center justify-center gap-2 transition-all shadow-lg shadow-emerald-500/20"
              >
                <Play size={20} /> 今すぐ開始
              </button>
            ) : (
              <button 
                onClick={stopGeneration}
                disabled={isShuttingDown}
                className={`flex-1 font-bold rounded-xl p-4 flex items-center justify-center gap-2 transition-all shadow-lg ${
                  isShuttingDown 
                  ? 'bg-zinc-700 text-zinc-400 cursor-not-allowed'
                  : 'bg-gradient-to-r from-rose-500 to-rose-600 hover:from-rose-400 hover:to-rose-500 text-white shadow-rose-500/20'
                }`}
              >
                {isShuttingDown ? <Loader2 size={20} className="animate-spin" /> : <Square size={20} />}
                {isShuttingDown ? '停止中...' : '安全に停止'}
              </button>
            )}
          </div>
        </div>

        {/* Current Session Progress */}
        <div className="bg-zinc-900/80 border border-zinc-800 rounded-xl p-5 mb-6">
          <div className="flex justify-between text-sm mb-2">
            <span className="text-zinc-400">セッション進捗 ({stats.processed} / {targetCount})</span>
            <span className="text-indigo-400 font-bold">{progressPercent}%</span>
          </div>
          <div className="h-4 bg-zinc-800 rounded-full overflow-hidden relative">
            <div 
              className="absolute top-0 left-0 h-full bg-gradient-to-r from-indigo-500 to-purple-500 transition-all duration-500 ease-out"
              style={{ width: `${progressPercent}%` }}
            />
          </div>
          
          <div className="grid grid-cols-3 gap-4 mt-5">
            <div className="flex flex-col items-center p-3 bg-zinc-800/50 rounded-lg">
              <span className="text-emerald-400 text-2xl font-bold">{stats.success}</span>
              <span className="text-zinc-500 text-xs mt-1">成功</span>
            </div>
            <div className="flex flex-col items-center p-3 bg-zinc-800/50 rounded-lg">
              <span className="text-rose-400 text-2xl font-bold">{stats.fail}</span>
              <span className="text-zinc-500 text-xs mt-1">失敗/却下</span>
            </div>
            <div className="flex flex-col items-center p-3 bg-zinc-800/50 rounded-lg border border-emerald-500/20">
              <span className="text-emerald-300 text-2xl font-bold">{stats.published}</span>
              <span className="text-emerald-500/70 text-xs mt-1">新規公開</span>
            </div>
          </div>
        </div>

        {/* Phase 3: Demand & Auto Planner KPIs */}
        <div className="bg-gradient-to-r from-indigo-900/40 to-cyan-900/20 border border-cyan-500/30 rounded-xl p-5 mb-6">
          <div className="flex items-center gap-2 text-cyan-400 font-bold text-sm mb-4">
            <Radar size={18} /> Phase 3: Demand Radar & Business KPIs
          </div>
          <div className="grid grid-cols-3 md:grid-cols-6 gap-4 text-center">
            <div className="bg-black/40 rounded-lg p-3">
              <div className="text-[10px] text-zinc-400 mb-1">本日の検索数</div>
              <div className="text-xl font-bold text-white">{dbStats.todaySearchCount}</div>
            </div>
            <div className="bg-black/40 rounded-lg p-3 border border-amber-500/20">
              <div className="text-[10px] text-amber-400 mb-1">不足素材 (Need)</div>
              <div className="text-xl font-bold text-amber-500">{dbStats.needAssetCount}</div>
            </div>
            <div className="bg-black/40 rounded-lg p-3 border border-cyan-500/20">
              <div className="text-[10px] text-cyan-400 mb-1">自動生成候補</div>
              <div className="text-xl font-bold text-cyan-400">{dbStats.autoGenCandidates}</div>
            </div>
            <div className="bg-black/40 rounded-lg p-3">
              <div className="text-[10px] text-zinc-400 mb-1">生成成功率</div>
              <div className="text-xl font-bold text-white">{dbStats.qaPassRate}%</div>
            </div>
            <div className="bg-black/40 rounded-lg p-3">
              <div className="text-[10px] text-zinc-400 mb-1">DL数</div>
              <div className="text-xl font-bold text-white">{dbStats.totalDownloads}</div>
            </div>
            <div className="bg-black/40 rounded-lg p-3">
              <div className="text-[10px] text-zinc-400 mb-1">推定広告収益</div>
              <div className="text-xl font-bold text-emerald-400">¥{dbStats.estimatedAdRev.toFixed(0)}</div>
            </div>
          </div>
        </div>

        {/* Global Progress & Logs */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <h3 className="text-zinc-300 font-medium flex items-center gap-2">
              <Database size={16} /> 全体統計
            </h3>
            <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-5 space-y-4">
              <div className="grid grid-cols-2 gap-4 mb-2">
                <div>
                  <div className="text-zinc-500 text-xs">REAL Queued</div>
                  <div className="text-xl font-bold text-blue-400">{dbStats.realQueued}</div>
                </div>
                <div className="text-right">
                  <div className="text-zinc-500 text-xs">DRY_RUN Archived</div>
                  <div className="text-xl font-bold text-zinc-500">{dbStats.dryRunArchived}</div>
                </div>
                <div>
                  <div className="text-zinc-500 text-xs">QA Failed</div>
                  <div className="text-xl font-bold text-rose-400">{dbStats.globalQaFailed}</div>
                </div>
                <div className="text-right">
                  <div className="text-zinc-500 text-xs">Approved (公開済み)</div>
                  <div className="text-xl font-bold text-emerald-400">{dbStats.totalApproved}</div>
                </div>
              </div>
              
              <div className="pt-2 border-t border-zinc-800">
                <div className="flex justify-between text-xs mb-2">
                  <span className="text-zinc-400">目標100件への道標</span>
                  <span className="text-amber-400 font-bold">{dbStats.totalApproved} / 100</span>
                </div>
                <div className="h-2 bg-zinc-800 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-gradient-to-r from-amber-500 to-orange-400 transition-all duration-1000"
                    style={{ width: `${Math.min(100, Math.round((dbStats.totalApproved / 100) * 100))}%` }}
                  />
                </div>
              </div>
            </div>
          </div>
          
          <div className="space-y-4">
            <h3 className="text-zinc-300 font-medium flex items-center gap-2">
              <AlertTriangle size={16} /> リアルタイムログ
            </h3>
            <div className="bg-black/50 border border-zinc-800 rounded-xl p-4 h-48 overflow-y-auto font-mono text-xs space-y-2">
              {logs.length === 0 ? (
                <div className="text-zinc-600 h-full flex items-center justify-center">待機中...</div>
              ) : (
                logs.map((log, i) => (
                  <div key={i} className={`${log.includes('エラー') || log.includes('Failed') || log.includes('failed') ? 'text-rose-400' : log.includes('passed') || log.includes('成功') ? 'text-emerald-400' : 'text-zinc-400'}`}>
                    {log}
                  </div>
                ))
              )}
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
